In [1]:
print('Hello')

Hello


In [2]:
import numpy as np 

In [3]:
x=[[123],[4,5,6]]
print(x)

[[123], [4, 5, 6]]


In [5]:
y=np.array(x)
y

array([list([123]), list([4, 5, 6])], dtype=object)

In [8]:
np.zeros((3,2))+10

array([[10., 10.],
       [10., 10.],
       [10., 10.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(4,20)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(50).reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [19]:
np.linspace(0,1000,5)

array([   0.,  250.,  500.,  750., 1000.])

In [20]:
np.random.randn(5)

array([ 1.01005357, -0.25736299,  1.61487637, -0.2541203 , -2.4943195 ])

In [27]:
np.random.randint(1,300)

81

In [3]:
x=np.arange(1,12)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x[4]

5

In [5]:
x[-1]

11

In [6]:
x[2:5]

array([3, 4, 5])

In [7]:
y=x[5:10]=23
y

23

In [8]:
x

array([ 1,  2,  3,  4,  5, 23, 23, 23, 23, 23, 11])

# Indexing and slicing in 2d array 

In [9]:
x=np.arange(25).reshape(5,5)
x


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
x[2][2]

12

In [11]:
x[2,2]

12

In [12]:
x[0:2,2:]

array([[2, 3, 4],
       [7, 8, 9]])

In [13]:
y=np.arange(1,20)

In [14]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [15]:
y[y>12]

array([13, 14, 15, 16, 17, 18, 19])